version: "3.9"

services:
  app:
    build: .
    container_name: fastify_app
    restart: always
    ports:
      - "4000:4000"
    environment:
      MONGO_URI: mongodb://localhost:27017/seubanco
      MAIN_DATABASE: postgres
      JWT_SECRET: sua_chave_secreta
      DB_NAME: seu_nome_db
      DB_URL: postgres://usuario:senha@db:5432/seu_nome_db
    depends_on:
      - db

  db:
    image: postgres:16
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: seu_nome_db
      POSTGRES_USER: usuario
      POSTGRES_PASSWORD: senha
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
